version: '3'

services: 
  last_order:
    build: .
    image: misaka_net
    ports:
      - "8000:8000" # Map for now
    networks:
      - default
    expose:
      - 8000
      - 8001
    environment:
      NODE_TYPE: master
      NODE_INFO: |
        {
          "misaka1": {"type": "program"},
          "misaka2": {"type": "program"},
          "misaka3": {"type": "stack"}
        }
      CERT_FILE: ./openssl/service.pem
      KEY_FILE: ./openssl/service.key
    command: ./app

  misaka1:
    image: misaka_net
    expose:
      - 8001
    networks:
      - default
    environment: 
      NODE_TYPE: program
      MASTER_URI: last_order
      PROGRAM: |
        IN ACC
        ADD 1
        MOV ACC, misaka2:R0
        MOV R0, ACC
        OUT ACC
      CERT_FILE: ./openssl/service.pem
      KEY_FILE: ./openssl/service.key
    command: ./app
    
  misaka2:
    image: misaka_net
    expose:
      - 8001
    networks:
      - default
    environment: 
      NODE_TYPE: program
      MASTER_URI: last_order
      PROGRAM: |
        MOV R0, ACC
        ADD 1
        PUSH ACC, misaka3
        POP misaka3, ACC
        MOV ACC, misaka1:R0
      CERT_FILE: ./openssl/service.pem
      KEY_FILE: ./openssl/service.key
    command: ./app
    
  misaka3:
    image: misaka_net
    expose:
      - 8001
    networks:
      - default
    environment: 
      NODE_TYPE: stack
      CERT_FILE: ./openssl/service.pem
      KEY_FILE: ./openssl/service.key
    command: ./app

networks:
  default: