version: '3'

services: 
  last_order:
    build: .
    image: misaka_net
    ports:
      - "8000:8000" # Map for now
    networks:
      - default
    expose:
      - 8000
    environment:
      NODE_TYPE: master
      NODE_URIS: misaka1,misaka2,misaka3
    command: ./app

  misaka1:
    image: misaka_net
    expose:
      - 8000
    networks:
      - default
    environment: 
      NODE_TYPE: program
      PROGRAM: |
        ADD 1
        MOV ACC, misaka2:R0
        MOV R0, ACC
    command: ./app
    
  misaka2:
    image: misaka_net
    expose:
      - 8000
    networks:
      - default
    environment: 
      NODE_TYPE: program
      PROGRAM: |
        MOV R0, ACC
        ADD 1
        PUSH ACC, misaka3
        POP misaka3, ACC
        MOV ACC, misaka1:R0
    command: ./app
    
  misaka3:
    image: misaka_net
    expose:
      - 8000
    networks:
      - default
    environment: 
      NODE_TYPE: stack
    command: ./app

networks:
  default: