// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	GetInput(ctx context.Context, in *InputValueRequest, opts ...grpc.CallOption) (*ValueReply, error)
	SendOutput(ctx context.Context, in *OutputValueRequest, opts ...grpc.CallOption) (*CommandReply, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) GetInput(ctx context.Context, in *InputValueRequest, opts ...grpc.CallOption) (*ValueReply, error) {
	out := new(ValueReply)
	err := c.cc.Invoke(ctx, "/grpc.Master/GetInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SendOutput(ctx context.Context, in *OutputValueRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Master/SendOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility
type MasterServer interface {
	GetInput(context.Context, *InputValueRequest) (*ValueReply, error)
	SendOutput(context.Context, *OutputValueRequest) (*CommandReply, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (UnimplementedMasterServer) GetInput(context.Context, *InputValueRequest) (*ValueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInput not implemented")
}
func (UnimplementedMasterServer) SendOutput(context.Context, *OutputValueRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOutput not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_GetInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Master/GetInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetInput(ctx, req.(*InputValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SendOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutputValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SendOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Master/SendOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SendOutput(ctx, req.(*OutputValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInput",
			Handler:    _Master_GetInput_Handler,
		},
		{
			MethodName: "SendOutput",
			Handler:    _Master_SendOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/messenger.proto",
}

// ProgramClient is the client API for Program service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*CommandReply, error)
	SendValue(ctx context.Context, in *SendValueRequest, opts ...grpc.CallOption) (*CommandReply, error)
}

type programClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramClient(cc grpc.ClientConnInterface) ProgramClient {
	return &programClient{cc}
}

func (c *programClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Program/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Program/Pause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Program/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Program/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programClient) SendValue(ctx context.Context, in *SendValueRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Program/SendValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramServer is the server API for Program service.
// All implementations must embed UnimplementedProgramServer
// for forward compatibility
type ProgramServer interface {
	Run(context.Context, *RunRequest) (*CommandReply, error)
	Pause(context.Context, *PauseRequest) (*CommandReply, error)
	Reset(context.Context, *ResetRequest) (*CommandReply, error)
	Load(context.Context, *LoadRequest) (*CommandReply, error)
	SendValue(context.Context, *SendValueRequest) (*CommandReply, error)
	mustEmbedUnimplementedProgramServer()
}

// UnimplementedProgramServer must be embedded to have forward compatible implementations.
type UnimplementedProgramServer struct {
}

func (UnimplementedProgramServer) Run(context.Context, *RunRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedProgramServer) Pause(context.Context, *PauseRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedProgramServer) Reset(context.Context, *ResetRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedProgramServer) Load(context.Context, *LoadRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedProgramServer) SendValue(context.Context, *SendValueRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendValue not implemented")
}
func (UnimplementedProgramServer) mustEmbedUnimplementedProgramServer() {}

// UnsafeProgramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramServer will
// result in compilation errors.
type UnsafeProgramServer interface {
	mustEmbedUnimplementedProgramServer()
}

func RegisterProgramServer(s grpc.ServiceRegistrar, srv ProgramServer) {
	s.RegisterService(&_Program_serviceDesc, srv)
}

func _Program_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Program/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Program_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Program/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Program_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Program/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Program_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Program/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Program_SendValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).SendValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Program/SendValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).SendValue(ctx, req.(*SendValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Program_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Program",
	HandlerType: (*ProgramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Program_Run_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Program_Pause_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Program_Reset_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Program_Load_Handler,
		},
		{
			MethodName: "SendValue",
			Handler:    _Program_SendValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/messenger.proto",
}

// StackClient is the client API for Stack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StackClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Push(ctx context.Context, in *PushValueRequest, opts ...grpc.CallOption) (*CommandReply, error)
	Pop(ctx context.Context, in *PopValueRequest, opts ...grpc.CallOption) (*ValueReply, error)
}

type stackClient struct {
	cc grpc.ClientConnInterface
}

func NewStackClient(cc grpc.ClientConnInterface) StackClient {
	return &stackClient{cc}
}

func (c *stackClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Stack/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Stack/Pause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Stack/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Push(ctx context.Context, in *PushValueRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/grpc.Stack/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Pop(ctx context.Context, in *PopValueRequest, opts ...grpc.CallOption) (*ValueReply, error) {
	out := new(ValueReply)
	err := c.cc.Invoke(ctx, "/grpc.Stack/Pop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StackServer is the server API for Stack service.
// All implementations must embed UnimplementedStackServer
// for forward compatibility
type StackServer interface {
	Run(context.Context, *RunRequest) (*CommandReply, error)
	Pause(context.Context, *PauseRequest) (*CommandReply, error)
	Reset(context.Context, *ResetRequest) (*CommandReply, error)
	Push(context.Context, *PushValueRequest) (*CommandReply, error)
	Pop(context.Context, *PopValueRequest) (*ValueReply, error)
	mustEmbedUnimplementedStackServer()
}

// UnimplementedStackServer must be embedded to have forward compatible implementations.
type UnimplementedStackServer struct {
}

func (UnimplementedStackServer) Run(context.Context, *RunRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStackServer) Pause(context.Context, *PauseRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedStackServer) Reset(context.Context, *ResetRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedStackServer) Push(context.Context, *PushValueRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedStackServer) Pop(context.Context, *PopValueRequest) (*ValueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pop not implemented")
}
func (UnimplementedStackServer) mustEmbedUnimplementedStackServer() {}

// UnsafeStackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StackServer will
// result in compilation errors.
type UnsafeStackServer interface {
	mustEmbedUnimplementedStackServer()
}

func RegisterStackServer(s grpc.ServiceRegistrar, srv StackServer) {
	s.RegisterService(&_Stack_serviceDesc, srv)
}

func _Stack_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Stack/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Stack/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Stack/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Stack/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Push(ctx, req.(*PushValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Pop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Pop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Stack/Pop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Pop(ctx, req.(*PopValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stack_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Stack",
	HandlerType: (*StackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Stack_Run_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Stack_Pause_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Stack_Reset_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Stack_Push_Handler,
		},
		{
			MethodName: "Pop",
			Handler:    _Stack_Pop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/messenger.proto",
}
